name: Test dotfiles deployments

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy dotfiles
        run: ./install.sh

      - name: Test dotfiles deployments
        run: cd test; goss validate -f tap | tee goss_validate.tap

      - uses: pcolby/tap-summary@v1
        with:
          path: test/*.tap
          # summary-file: path/to/output/file.md
